name: GeoIPTools
main: uk.org.whoami.geoip.GeoIPTools
version: 0.2
commands:
    geoupdate:
        description: Update the GeoIPDatabase files
        usage: /geoupdate
permissions:
    geoiptools.*:
        description: Gives access to all GeoIPTools commands
        children:
            geoiptools.geoupdate: true
    geoiptools.geoupdate:
        description: Updates the database
        default: op